routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

$adminRoute = config('app.admin_url');

$webRoute = config('app.web_url');

Route::get('/script/moveChatOldToNew', 'ScriptController@moveChatOldToNew')->name('moveChatOldToNew');

Route::get('test', 'IndexController@test')->name('test');
Route::group(['prefix' => $webRoute, 'namespace' => 'Web', 'as' => 'web.'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login-user', 'Auth\LoginController@login')->name('loginUser');
    Route::post('/social-register', 'Auth\LoginController@socialRegister')->name('socialRegister');
    Route::get('/register-user', 'Auth\RegisterController@index')->name('register');
    Route::post('/register-submit', 'Auth\RegisterController@register')->name('registerUser');
    Route::get('/logout-user', 'WebController@logout')->name('logout');
    Route::get('/login-email-verify/{email}', 'Auth\LoginController@loginEmailVerify')->name('login-email-verify');

    Route::get('/email-verify/{user}', 'Auth\RegisterController@emailVerify', function (Request $request) {
        if (!$request->hasValidSignature()) {
            abort(401);
        }

    })->name('email-verify')->middleware('signed');

    // Password Reset Routes...
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/user-password-changed', 'ForgotPasswordController@passwordChanged')->name('passwordChanged');
        Route::get('/set-password/{user}', 'ForgotPasswordController@setPassword', function (Request $request) {
            if (!$request->hasValidSignature()) {
                abort(401);
            }

        })->name('set-password')->middleware('signed');
    });

    Route::get('/', 'WebController@home')->name('home');
    Route::get('/front/video/{id}', 'WebController@videoInfo')->name('videoInfo');
    Route::get('/front/video/view/{id}', 'WebController@videoViewed')->name('videoViewed');
    Route::get('/front/video/comments/{id}/{type}', 'WebController@videoComments')->name('videoComments');
    Route::get('/privacy-policy', 'PageController@index')->name('privacy-policy')->defaults('slug', 'privacy-policy');
    Route::get('/terms', 'PageController@index')->name('terms')->defaults('slug', 'terms');
    Route::get('/data-delete', 'PageController@index')->name('data-delete')->defaults('slug', 'data-delete');

    Route::group(['middleware' => ['auth:web']], function () {
        Route::post('/front/video/comments/{id}', 'WebController@videoPostComments')->name('videoPostComments');
        Route::get('/front/video/like/{id}', 'WebController@videoLike')->name('videoLike');
        Route::get('/edit-profile/{id}', 'UserController@editUserProfile')->name('editUserProfile');
        Route::post('/edit-profile/{id}', 'UserController@updateUserProfile')->name('updateUserProfile');
        Route::get('/remove-profile-pic', 'UserController@removeProfilePic')->name('removeProfilePic');
        Route::get('/user-follow/{id}', 'UserController@followUnfollowUser')->name('followUnfollowUser');
        Route::get('/user-block/{id}', 'UserController@blockUnblock')->name('blockUnblock');
        Route::get('/notifications', 'UserController@userNotifications')->name('userNotifications');
        Route::get('/notificationStatus', 'UserController@notificationStatus')->name('notificationStatus');

        //upload videos
        Route::get('/upload-video', 'UserController@uploadVideo')->name('uploadVideo');
        Route::post('/upload-video', 'UserController@insertVideo')->name('insertVideo');
        Route::post('/delete-video', 'UserController@deleteVideo')->name('deleteVideo');
        Route::get('/video-info-update/{id?}', 'UserController@videoInfoUpdate')->name('video-info-update');
        Route::post('/video-info-submit', 'UserController@videoInfoSubmit')->name('video-info-submit');

        //password change
        Route::get('/change-password', 'UserController@changePassword')->name('changePassword');
        Route::post('/update-password', 'UserController@updatePassword')->name('updatePassword');

        Route::get('followers-list/{id}', 'UserController@followersList')->name('followers-list');
        Route::get('following-list/{id}', 'UserController@followingList')->name('following-list');
        Route::get('blocked-user-list', 'UserController@blockUsersList')->name('blocked-user-list');
        //messenger
        Route::get('/messages', 'MessagesController@index')->name('messages');
        Route::get('/messages/chat/{conversation}', 'MessagesController@chatMessages')->name('messages.chat');
        Route::post('/messages/store/{conversation}', 'MessagesController@storeMessage')->name('messages.store');
        Route::post('/typing/{id}', 'MessagesController@typingMessage')->name('messages.typing');
        Route::post('/message/read/{conversation}', 'MessagesController@readMessage')->name('messages.readMessage');
        Route::post('/messages/delete', 'MessagesController@deleteMessage')->name('messages.messagesDelete');

        Route::get('/conversation/store/{user_id}', 'ConversationController@store')->name('conversation.store');
        Route::get('/conversation/get', 'ConversationController@index')->name('conversation.get');
        Route::post('/conversation/delete', 'ConversationController@deleteMessage')->name('conversation.deleteMessage');

    });

    //Social login
    Route::get('auth/google', 'Auth\LoginController@redirectToGoogle')->name('googleLogin');
    Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback')->name('googleCallback');

    Route::get('auth/facebook', 'Auth\LoginController@redirectToFacebook')->name('facebookLogin');
    Route::get('auth/facebook/callback', 'Auth\LoginController@handleFacebookCallback')->name('facebookCallback');

    Route::get('/profile/{id}', 'UserController@userProfile')->name('userProfile');

    //firebase notification
    Route::post('/save-token', 'NotificationController@saveToken')->name('saveToken');
    Route::post('/send-notification', 'NotificationController@sendNotification')->name('sendNotification');
    Route::get('/test-notification', 'NotificationController@testNotification')->name('testNotification');

    Route::get('/leuke-search', 'UserController@leukeSearch')->name('leukeSearch');
    Route::get('search-all', 'WebController@searchAll')->name('searchAll');
    Route::get('tag-videos/{val}', 'WebController@searchTagVideos')->name('tagVideos');
});

Route::group(['prefix' => $adminRoute, 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    // Routes without auth check for guest customers
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('loginPost');
    Route::get('/register', 'Auth\RegisterController@index')->name('register');
    Route::post('/register', 'Auth\RegisterController@register')->name('registerPost');
    Route::get('/logout', 'AdminController@logout')->name('logout');

    // Routes with auth check for logged in admin
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/change_password/', 'AdminController@changePassword')->name('change_password.index')->middleware('app_version_check');
        Route::post('/update_password/', 'AdminController@updatePassword')->name('change_password.update');

        // categories management system ( Listing, Add, Edit, Delete , Copy )
        Route::resource('categories', 'CategoryController');
        Route::post('/categories/delete', 'CategoryController@delete')->name('categories_delete');
        Route::get('/categories/create/{category_id?}', 'CategoryController@create')->name('categories_create');
        Route::get('/categories/{category_id}/view', 'CategoryController@view')->name('categories_view');
        Route::get('/categories/{category_id}/copy', 'CategoryController@copyContent')->name('categories_copy');
        Route::get('/categories/{category_id}/edit', 'CategoryController@edit')->name('categories_edit');
        Route::post('/categories/server_processing', 'CategoryController@serverProcessing')->name('categories_server_processing');

        Route::resource('sounds', 'SoundController');
        Route::post('/sounds/delete', 'SoundController@delete')->name('sounds_delete');
        Route::post('/sounds/select_cat', 'SoundController@select_cat')->name('sounds_select_cat');
        Route::post('/sounds/create', 'SoundController@create')->name('sounds_create');
        Route::get('/sounds/{user_id}/copy', 'SoundController@copyContent')->name('sounds_copy');
        Route::get('/sounds/{user_id}/view', 'SoundController@view')->name('sounds_view');
        Route::get('/sounds/detail/{payment_id}', 'SoundController@detail')->name('sounds_detail');
        Route::post('/sounds/server_processing', 'SoundController@serverProcessing')->name('sounds_server_processing');
        Route::post('/sounds/audio_play', 'SoundController@audio_play')->name('audio_play');

        Route::resource('videos', 'VideoController');
        Route::post('/videos/delete', 'VideoController@delete')->name('videos_delete');
        Route::post('/videos/create', 'VideoController@create')->name('videos_create');

resources/views/web/followersList.blade.php
@extends('layouts.front')

@section('content')
<style>
 .bg-btn{
        /* background: linear-gradient(50deg, rgb(115,80,199) 0%, rgb(236,74,99) 100%); */
		
		padding: 10px 0;
    color: #fff;
    border-radius: 2px;
    }
	.card .card-body .message {
		padding-left: 80px;
		text-align: left;
	}
.avatar_img{
	width: 57px;
	/* width: 7%; */
}
.card .card-body .actions {
  margin-top: 5px;
}
</style>
@include('includes.topbar')
	<section class="h4-about s-padding ">
		
		<div class="container">
			<div class="row align-items-center">

				<div class="col-lg-12">
					<div>
					
					<div class="container-fluid">
						<div class="row m-3 mb-5 user_profile_top">
						<div class="col-md-3">
						<?php if(!empty($userInfo->user_dp)){
							if(strpos($userInfo->user_dp,'fbsbx.com') !== false || strpos($userInfo->user_dp,'googleusercontent.com') !== false){
								$user_dp=$userInfo->user_dp;
							}else{
								// $exists = Storage::disk(config('app.filesystem_driver'))->exists('public/profile_pic/'.$userInfo->user_id.'/small/'.$userInfo->user_dp);
								//dd(Storage::url('public/profile_pic/' . $userInfo->user_id). '/small/' . $userInfo->user_dp);
								// if($exists){ 
								// if(file_exists(public_path('storage/profile_pic').'/'.$userInfo->user_id.'/small/'.$userInfo->user_dp)){
									$user_dp=asset(Storage::url('public/profile_pic/' . $userInfo->user_id). '/small/' . $userInfo->user_dp);
								// }else{
								//     $user_dp=asset('storage/profile_pic/default.png');
								// } 
							}  
						}else{
							$user_dp=asset('default/default.png');
						} ?>
							<img class="rounded-circle" style="box-shadow: 0px 0px 6px #774fc3;" src="{{ $user_dp }}" alt="" width="150" height="150"/>
						</div>
						<div class="col-md-9 pt-2 p-0">
							<div class="">
								<h3 style="text-transform: capitalize;">{{ $userInfo->fname }} {{ $userInfo->lname }}</h3> 
							
							</div>
							<h5 style="color:#aaa">{{ '@'.$userInfo->username }}  <?php if($userInfo->verified=='A'){ ?>
											<img src="{{ asset('default/verified-icon-blue.png') }}" alt="" style="width:15px;height:15px;">
										<?php } ?></h5> 
							<div class="row mb-3"> 
								<div class="col-lg-3 col-3"><strong>{{ !empty($userInfo->total_videos) ? $userInfo->total_videos : '0' }}</strong> videos</div>
								<div class="col-lg-3 col-3"><strong>{{ !empty($userInfo->total_likes) ? $userInfo->total_likes : '0' }}</strong> likes</div>
								<div class="col-lg-3 col-3"><a href="{{ route('web.followers-list',$userInfo->user_id)}}" style="color:#5f6368;cursor:pointer"><strong>{{ $followers }}</strong> followers</a></div>
								<div class="col-lg-3 col-3"><a href="{{ route('web.following-list',$userInfo->user_id)}}" style="color:#5f6368;cursor:pointer"><strong>{{ $following }}</strong> following</a></div>
							</div>
							<div class="row">
								<div class="col-md-3 ">
									@if (auth()->guard('web')->check())
										@if (auth()->guard('web')->user()->user_id == $userInfo->user_id)
											<a class="btn btn-blue bg-btn text-white" href="{{ route('web.editUserProfile', $userInfo->user_id) }}" style="{{MyFunctions::getTopbarColor()}};min-width: 110px;padding:6px 0px;"><i class="fa fa-edit"></i> Edit Profile</a>
										@endif
									@endif
									@if ($canFollow)
										<a class="btn bg-btn text-white" onclick="followUnfollow('{{ $userInfo->user_id }}')" style="min-width: 110px;padding:6px 0px;{{MyFunctions::getTopbarColor()}}">
											<span id="followUnfollowIcon">
												<?php if(!$followed){ ?>
												<i class="fa fa-user-plus"></i>
												<?php }else{ ?>
													<i class="fa fa-user-times"></i>
												<?php } ?>
											</span>
											<span id="followUnfollow">
											@if(!$followed) Follow @else Unfollow @endif</span>
										</a>
									@endif
								</div>
								@if (auth()->guard('web')->check())
									@if (auth()->guard('web')->user()->user_id != $userInfo->user_id)
										<div class="col-md-3">
											<a onclick="blockUnblock('{{ $userInfo->user_id }}')" class="btn bg-btn text-white" style="min-width: 110px;padding:6px 0px;{{MyFunctions::getTopbarColor()}}">
											<span id="blockUnblockIcon">
											<?php if(!$blocked){ ?>
												<i class="fa fa-ban"></i>
											<?php }else{ ?>
												<i class="fa fa-check-circle"></i>
											<?php } ?>        
											</span>
											<span id="blockUnblock">
												@if(!$blocked) Block @else Unblock @endif
											</span>
											</a>
										</div>
									@endif
								@endif
							</div>
						</div>
						
					</div>
					<hr>
						<div class="row">
							<div class="col-lg-9">
									<h3>Followers</h3><br />

									<div id="follow">
										<?php
										if(count($followersList)>0){
										foreach($followersList as $follower){ ?>
											
											<div class="card">
												<div class="card-body">
												<?php 
												if($follower->user_dp!=""){
													if(strpos($follower->user_dp,'facebook.com') !== false || strpos($follower->user_dp,'fbsbx.com') !== false || strpos($follower->user_dp,'googleusercontent.com') !== false){ 
														$u_dp=$follower->user_dp;
														}else{
															$u_dp=asset(Storage::url('public/profile_pic').'/'.$follower->user_id.'/small/'.$follower->user_dp) ;
															
														} 
													}else{ 
														$u_dp= asset('default/default.png');
													} ?>
												<img src="{{$u_dp}}" class="avatar_img float-left rounded-circle">
												<div class="message">
													<h5 class="card-title"><a href="{{ route('web.userProfile', $follower->user_id) }}">{{ $follower->fname.' '.$follower->lname }} <?php if($follower->verified=='A'){ ?>
														<img src="{{ asset('default/verified-icon-blue.png') }}" alt="" style="width:15px;height:15px;">
													<?php } ?></a></h5>
													<h6 class="card-subtitle mb-2 text-muted">{{ '@' . $follower->username }}</h6>
													<?php if($follower->user_id != auth()->guard('web')->user()->user_id){ 
														 ?>
														<span class="follow_btn" data-id="<?php echo $follower->user_id; ?>" style="{{MyFunctions::getTopbarColor()}}">
															<?php if($follower->follow>0){
																echo "Unfollow";
															}else{
																echo "Follow";
															} ?>
														</span>
													<?php } ?>
													<!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
												</div>
												<!-- <div class="actions">
													<a href="#" class="card-link">Like</a>
													<a href="#" class="card-link">Reply</a>
													<a href="#" class="card-link">Share</a>
												</div> -->
												</div>
											</div>
										<?php } 
										}else{ ?>				
											<div class="card">
												<div class="card-body">
													<h6>No Follower...</h6>
												</div>
											</div>
										<?php } ?>										
									</div>

									<div class="loadMore text-center col-12">
										<img src="{{ asset('default/loading.gif') }}" style="width:35px;margin-top:10px;">
									</div>

								<br/>
							</div>
							
						<div class="col-lg-3">
							@include('includes.leftSidebar')
							
							</div>
						</div>
					</div>

					</div>
				</div>
			</div>
		</div>
		<div class="floating-shapes">
			<span data-parallax='{"x": 150, "y": -20, "rotateZ":500}'><img src="{{ asset('default/fl-shape-1.png') }}" alt=""></span>
			<span data-parallax='{"x": 250, "y": 150, "rotateZ":500}'><img src="{{ asset('default/fl-shape-2.png') }}" alt=""></span>
			<span data-parallax='{"x": -180, "y": 80, "rotateY":2000}'><img src="{{ asset('default/fl-shape-3.png') }}" alt=""></span>
			<span data-parallax='{"x": -20, "y": 180}'><img src="{{ asset('default/fl-shape-4.png') }}" alt=""></span>
			<span data-parallax='{"x": 300, "y": 70}'><img src="{{ asset('default/fl-shape-5.png') }}" alt=""></span>
			<span data-parallax='{"x": 250, "y": 180, "rotateZ":1500}'><img src="{{ asset('default/fl-shape-6.png') }}" alt=""></span>
			<span data-parallax='{"x": 180, "y": 10, "rotateZ":2000}'><img src="{{ asset('default/fl-shape-7.png') }}" alt=""></span>
			<span data-parallax='{"x": 250, "y": -30, "rotateX":2000}'><img src="{{ asset('default/fl-shape-8.png') }}" alt=""></span>
			<span data-parallax='{"x": 60, "y": -100}'><img src="{{ asset('default/fl-shape-9.png') }}" alt=""></span>
			<span data-parallax='{"x": -30, "y": 150, "rotateZ":1500}'><img src="{{ asset('default/fl-shape-10.png') }}" alt=""></span>
		</div>
	</section><!-- about -->

@endsection

resources/views/web/messages.blade.php
@extends('layouts.front')

@section('content')
@include('includes.topbar')
@include('layouts.messages.headLinks')
<div class="container message-container">
    <div class="row message-row">
        <div class="col-4 left-message-bar">
            <ul class="nav nav-pills my-3 row" id="pills-tab" role="tablist">
                <li class="nav-item col-6 text-center">
                    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Chats</a>
                </li>
                <li class="nav-item col-6 text-center">
                    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">People</a>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                @include('layouts.messages.leftMessageBar')
                
            </div>
        </div>
        <div class="col-8">
            <div class="row ">
          

            </div>
        </div>

        @include('layouts.messages.footerLinks')
        @endsection

resources/views/web/notifications.blade.php
@extends('layouts.front')

@section('content')

@include('includes.topbar')

<div class="container mb-5">
    <h3 class="m-5 text-danger text-center">Notifications</h3>
        {{-- @foreach ($notifications as $notification)
        @php
            $profileImg = '';
            if(!empty($notification->user_dp)) {
                if($notification->login_type == 'O') {
                $profileImg =  asset('storage/profile_pic/' . $notification->user_id) . '/small/' . $notification->user_dp;
                } else {
                $profileImg = $notification->user_dp; 
                }
            } else {
                $profileImg = asset('default/default.png');
            }
        @endphp
            <div class="row text-left border-bottom mt-2 pb-2">
                 <div class="col-lg-2 col-sm-2 col-2 pt-1 text-center">
                {{-- <img src="{{ $profileImg }}" class="w-50 rounded-circle"> --}}
                {{-- <img onclick="window.location.href='{{ route("web.userProfile", $notification->user_id) }}';" src="{{ $profileImg }}" class="w-50 rounded-circle link">
                </div>
                <div class="col-lg-8 col-sm-8 col-8">
                    <strong class="text-info"><span class="link" onclick="window.location.href='{{ route("web.userProfile", $notification->user_id) }}';">ee{{ $notification->username }}
                    <?php if($notification->verified=='A'){ ?>
								<img src="{{ asset('default/verified-icon-blue.png') }}" alt="" style="width:15px;height:15px;">
							<?php } ?>
                    </span></strong>
                    @if ($notification->notify_total > 1)
														and {{ $notification->notify_total - 1 }} other
                                                    @endif
                    <br />{{ $notification->message }} <br />
                    <small class="text-warning">{{ \Carbon\Carbon::createFromTimeStamp(strtotime($notification->added_on))->diffForHumans() }}</small>
                </div>
            </div>
        @endforeach --}}

        @if (!empty($notifications))
        @foreach ($notifications as $notification)
                @php
                    $profileImg = '';
                    if (!empty($notification->profileImg)) {
                        $profileImg = $notification->profileImg;
                    } else {
                        if(!empty($notification->user_dp)) {
                            if($notification->login_type == 'O') {
                            $profileImg =  asset('storage/profile_pic/' . $notification->user_id) . '/small/' . $notification->user_dp;
                            } else {
                            $profileImg = $notification->user_dp; 
                            }
                        } else {
                            $profileImg = asset('default/default.png');
                        }
                    }
                @endphp
                <div class="col-md-6 col-12 offset-lg-3">
                    <div class="row text-left border-bottom pb-1" style="@if($notification->read == 0)background: beige;@endif">
                        <div class="col-lg-3 col-3 pt-1 text-center">
                            <img width="60px;" onclick="window.location.href='{{ route("web.userProfile", $notification->user_id) }}';" src="{{ $profileImg }}" class="rounded-circle link">
                        </div>
                        <div class="col-lg-9 col-9">
                            {{-- <a href="{{ route('web.home') }}"> --}}
                                <strong class="text-info"><span class="link" onclick="window.location.href='{{ route("web.userProfile", $notification->user_id) }}';">{{ $notification->username }}
                                <?php if($notification->verified=='A'){ ?>
								<img src="{{ asset('default/verified-icon-blue.png') }}" alt="" style="width:15px;height:15px;">
							<?php } ?></span></strong>
                            {{-- </a> --}}
                            @if ($notification->notify_total > 1)
                                and {{ $notification->notify_total - 1 }} other
                            @endif
                            <br />{{ $notification->message }} <br />
                            <small class="text-warning">{{ \Carbon\Carbon::createFromTimeStamp(strtotime($notification->added_on))->diffForHumans() }}</small>
                            @if ($notification->type == 'F')
                            <div onclick="window.location.href='{{ route('web.userProfile', ['id' => $notification->notify_to, 'notify_ids' => $notification->notify_ids]) }}'" style="position: absolute;top: 0px;height: 70%;width: 100%;z-index: 100;margin-top: 8%;"></div>
                            @else
                                <div onclick="window.location.href='{{ route('web.home', ['videoId' => $notification->video_id, 'notify_ids' => $notification->notify_ids]) }}'" style="position: absolute;top: 0px;height: 70%;width: 100%;z-index: 100;margin-top: 8%;"></div>
                            @endif
                        </div>
                    </div>
                </div>
        @endforeach
        <div class="mt-3 d-flex justify-content-center"> {{ $notifications->links() }} </div>
        @endif
   
</div>
	  
<script type="text/javascript">
</script>

@endsection

resources/views/web/testNotification.blade.php
@extends('layouts.web')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <center>
                <button id="btn-nft-enable" onclick="initFirebaseMessagingRegistration()" class="btn btn-danger btn-xs btn-flat">Allow for Notification</button>
            </center>
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{ route('web.sendNotification') }}" method="POST" id="notifyForm">
                        @csrf
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" class="form-control" name="title">
                        </div>
                        <div class="form-group">
                            <label>Body</label>
                            <textarea class="form-control" name="body"></textarea>
                          </div>
                        <button type="submit" class="btn btn-primary">Send Notification</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://www.gstatic.com/firebasejs/7.23.0/firebase.js"></script>
<script>


    var firebaseConfig = {
        apiKey: "AIzaSyDeFvP6X8Twx8UnrFIrV5C2oZzMZ9Fc53U",
        authDomain: "leukeapp.firebaseapp.com",
        databaseURL: "https://leukeapp.firebaseio.com",
        projectId: "leukeapp",
        storageBucket: "leukeapp.appspot.com",
        messagingSenderId: "1020512047352",
        appId: "1:1020512047352:web:4657cb1afed7f12dcceb0d",
        measurementId: "G-NS5HP11S9H"
    };
    // measurementId: G-R1KQTR3JBN
      // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    const messaging = firebase.messaging();

    // $('#notifyForm').on('submit', function(e) {
	// 		e.preventDefault();alert('abc');
	// 		form_data = $(this).serialize();
	// 		formUrl = $('#notifyForm').prop('action');alert(formUrl);
	// 		$.ajax({
	// 			url : formUrl,
	// 			type : 'POST',
	// 			datatype : 'json',
	// 			data : form_data,
	// 			success: function(data) {
	// 				if (data.success) {
	// 					$('#video_comment').val('');
	// 					$("#modal-comment-list").animate({ scrollTop: $('#modal-comment-list').prop("scrollHeight")}, 1000);
	// 					videoComments('insert');
	// 				}
	// 			},
	// 			error: function(data) {
	// 				if (data.status == 401) {
	// 					window.location.href = "{{ route('web.login') }}";
	// 				}
	// 			}
	// 		});
	// 	});

    function initFirebaseMessagingRegistration() {
            messaging
            .requestPermission()
            .then(function () {
                return messaging.getToken()
            })
            .then(function(token) {
                console.log(token);

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                });

                $.ajax({
                    url: '{{ route("web.saveToken") }}',
                    type: 'POST',
                    data: {
                        token: token
                    },
                    dataType: 'JSON',
                    success: function (response) {
                        // alert(response.msg);
                    },
                    error: function (err) {
                        console.log('User Chat Token Error'+ err);
                    },
                });

            }).catch(function (err) {
                toastr.error('User Chat Token Error'+ err, null, {timeOut: 3000, positionClass: "toast-bottom-right"});
            });
     }  
    

    messaging.onMessage(function(payload) {
        const noteTitle = payload.notification.title;
        const noteOptions = {
            body: payload.notification.body,
            icon: payload.notification.icon,
        };
        new Notification(noteTitle, noteOptions);
    });

</script>
@endsection

resources/views/web/testPusherNot.blade.php
<!DOCTYPE html>
    <head>
    <title>Laravel Real Time Notification Tutorial With Example</title>
    <h1>Laravel Real Time Notification Tutorial With Example</h1>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script>
    Pusher.logToConsole = true;

var pusher = new Pusher('{{ config("app.pusher_app_key") }}', {
      cluster: '{{ config("app.pusher_app_cluster") }}',
      encrypted: true
    });



    var channel = pusher.subscribe('my-channel');
    channel.bind('pusher:subscription_succeeded', function(members) {
        // alert('successfully subscribed!');
    });
    channel.bind('my-event', function(data) {
      alert(JSON.stringify(data));
    });
    </script>
    </head>
</html>