routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

$adminRoute = config('app.admin_url');

$webRoute = config('app.web_url');

Route::get('/script/moveChatOldToNew', 'ScriptController@moveChatOldToNew')->name('moveChatOldToNew');

Route::get('test', 'IndexController@test')->name('test');
Route::group(['prefix' => $webRoute, 'namespace' => 'Web', 'as' => 'web.'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login-user', 'Auth\LoginController@login')->name('loginUser');
    Route::post('/social-register', 'Auth\LoginController@socialRegister')->name('socialRegister');
    Route::get('/register-user', 'Auth\RegisterController@index')->name('register');
    Route::post('/register-submit', 'Auth\RegisterController@register')->name('registerUser');
    Route::get('/logout-user', 'WebController@logout')->name('logout');
    Route::get('/login-email-verify/{email}', 'Auth\LoginController@loginEmailVerify')->name('login-email-verify');

    Route::get('/email-verify/{user}', 'Auth\RegisterController@emailVerify', function (Request $request) {
        if (!$request->hasValidSignature()) {
            abort(401);
        }

    })->name('email-verify')->middleware('signed');

    // Password Reset Routes...
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/user-password-changed', 'ForgotPasswordController@passwordChanged')->name('passwordChanged');
        Route::get('/set-password/{user}', 'ForgotPasswordController@setPassword', function (Request $request) {
            if (!$request->hasValidSignature()) {
                abort(401);
            }

        })->name('set-password')->middleware('signed');
    });

    Route::get('/', 'WebController@home')->name('home');
    Route::get('/front/video/{id}', 'WebController@videoInfo')->name('videoInfo');
    Route::get('/front/video/view/{id}', 'WebController@videoViewed')->name('videoViewed');
    Route::get('/front/video/comments/{id}/{type}', 'WebController@videoComments')->name('videoComments');
    Route::get('/privacy-policy', 'PageController@index')->name('privacy-policy')->defaults('slug', 'privacy-policy');
    Route::get('/terms', 'PageController@index')->name('terms')->defaults('slug', 'terms');
    Route::get('/data-delete', 'PageController@index')->name('data-delete')->defaults('slug', 'data-delete');

    Route::group(['middleware' => ['auth:web']], function () {
        Route::post('/front/video/comments/{id}', 'WebController@videoPostComments')->name('videoPostComments');
        Route::get('/front/video/like/{id}', 'WebController@videoLike')->name('videoLike');
        Route::get('/edit-profile/{id}', 'UserController@editUserProfile')->name('editUserProfile');
        Route::post('/edit-profile/{id}', 'UserController@updateUserProfile')->name('updateUserProfile');
        Route::get('/remove-profile-pic', 'UserController@removeProfilePic')->name('removeProfilePic');
        Route::get('/user-follow/{id}', 'UserController@followUnfollowUser')->name('followUnfollowUser');
        Route::get('/user-block/{id}', 'UserController@blockUnblock')->name('blockUnblock');
        Route::get('/notifications', 'UserController@userNotifications')->name('userNotifications');
        Route::get('/notificationStatus', 'UserController@notificationStatus')->name('notificationStatus');

        //upload videos
        Route::get('/upload-video', 'UserController@uploadVideo')->name('uploadVideo');
        Route::post('/upload-video', 'UserController@insertVideo')->name('insertVideo');
        Route::post('/delete-video', 'UserController@deleteVideo')->name('deleteVideo');
        Route::get('/video-info-update/{id?}', 'UserController@videoInfoUpdate')->name('video-info-update');
        Route::post('/video-info-submit', 'UserController@videoInfoSubmit')->name('video-info-submit');

        //password change
        Route::get('/change-password', 'UserController@changePassword')->name('changePassword');
        Route::post('/update-password', 'UserController@updatePassword')->name('updatePassword');

        Route::get('followers-list/{id}', 'UserController@followersList')->name('followers-list');
        Route::get('following-list/{id}', 'UserController@followingList')->name('following-list');
        Route::get('blocked-user-list', 'UserController@blockUsersList')->name('blocked-user-list');
        //messenger
        Route::get('/messages', 'MessagesController@index')->name('messages');
        Route::get('/messages/chat/{conversation}', 'MessagesController@chatMessages')->name('messages.chat');
        Route::post('/messages/store/{conversation}', 'MessagesController@storeMessage')->name('messages.store');
        Route::post('/typing/{id}', 'MessagesController@typingMessage')->name('messages.typing');
        Route::post('/message/read/{conversation}', 'MessagesController@readMessage')->name('messages.readMessage');
        Route::post('/messages/delete', 'MessagesController@deleteMessage')->name('messages.messagesDelete');

        Route::get('/conversation/store/{user_id}', 'ConversationController@store')->name('conversation.store');
        Route::get('/conversation/get', 'ConversationController@index')->name('conversation.get');
        Route::post('/conversation/delete', 'ConversationController@deleteMessage')->name('conversation.deleteMessage');

    });

    //Social login
    Route::get('auth/google', 'Auth\LoginController@redirectToGoogle')->name('googleLogin');
    Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback')->name('googleCallback');

    Route::get('auth/facebook', 'Auth\LoginController@redirectToFacebook')->name('facebookLogin');
    Route::get('auth/facebook/callback', 'Auth\LoginController@handleFacebookCallback')->name('facebookCallback');

    Route::get('/profile/{id}', 'UserController@userProfile')->name('userProfile');

    //firebase notification
    Route::post('/save-token', 'NotificationController@saveToken')->name('saveToken');
    Route::post('/send-notification', 'NotificationController@sendNotification')->name('sendNotification');
    Route::get('/test-notification', 'NotificationController@testNotification')->name('testNotification');

    Route::get('/leuke-search', 'UserController@leukeSearch')->name('leukeSearch');
    Route::get('search-all', 'WebController@searchAll')->name('searchAll');
    Route::get('tag-videos/{val}', 'WebController@searchTagVideos')->name('tagVideos');
});

Route::group(['prefix' => $adminRoute, 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    // Routes without auth check for guest customers
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('loginPost');
    Route::get('/register', 'Auth\RegisterController@index')->name('register');
    Route::post('/register', 'Auth\RegisterController@register')->name('registerPost');
    Route::get('/logout', 'AdminController@logout')->name('logout');

    // Routes with auth check for logged in admin
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/change_password/', 'AdminController@changePassword')->name('change_password.index')->middleware('app_version_check');
        Route::post('/update_password/', 'AdminController@updatePassword')->name('change_password.update');

        // categories management system ( Listing, Add, Edit, Delete , Copy )
        Route::resource('categories', 'CategoryController');
        Route::post('/categories/delete', 'CategoryController@delete')->name('categories_delete');
        Route::get('/categories/create/{category_id?}', 'CategoryController@create')->name('categories_create');
        Route::get('/categories/{category_id}/view', 'CategoryController@view')->name('categories_view');
        Route::get('/categories/{category_id}/copy', 'CategoryController@copyContent')->name('categories_copy');
        Route::get('/categories/{category_id}/edit', 'CategoryController@edit')->name('categories_edit');
        Route::post('/categories/server_processing', 'CategoryController@serverProcessing')->name('categories_server_processing');

        Route::resource('sounds', 'SoundController');
        Route::post('/sounds/delete', 'SoundController@delete')->name('sounds_delete');
        Route::post('/sounds/select_cat', 'SoundController@select_cat')->name('sounds_select_cat');
        Route::post('/sounds/create', 'SoundController@create')->name('sounds_create');
        Route::get('/sounds/{user_id}/copy', 'SoundController@copyContent')->name('sounds_copy');
        Route::get('/sounds/{user_id}/view', 'SoundController@view')->name('sounds_view');
        Route::get('/sounds/detail/{payment_id}', 'SoundController@detail')->name('sounds_detail');
        Route::post('/sounds/server_processing', 'SoundController@serverProcessing')->name('sounds_server_processing');
        Route::post('/sounds/audio_play', 'SoundController@audio_play')->name('audio_play');

        Route::resource('videos', 'VideoController');
        Route::post('/videos/delete', 'VideoController@delete')->name('videos_delete');
        Route::post('/videos/create', 'VideoController@create')->name('videos_create');

resources/views/admin/admin-app-version-warning.blade.php
@extends('layouts.admin')
@section('content')
<?php
    $title = 'Demo Version';
  

?>
<style>
.card{
    min-height:450px;
    margin-top: 0px;
}
</style>
<section class="rightside-main">
    <div class="container-fluid">
        <div class="page-top">
            <div class="page-header borderless">
                <h4><?php echo $title; ?></h4>   
            </div>
            <div class="page-berdcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard')}}">
                            <i class="fa fa-home"></i> Dashboard
                        </a>
                    </li>
                    <!-- <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard')}}">Dashboard</a>
                    </li> -->
                    <li class="breadcrumb-item">
                        <a href="#">{{$title}}</a>
                    </li>
                </ul>       
            </div>
        </div>
        <div class="row">
  
            <div class="col-md-12 pl-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card table-card">
                            <div class="card-header borderless">
                                <h3><?php echo $title;?></h3>
                            </div>
                            <div class="card-body">
                                <h6>This Feature Is Not Available For Demo Version.</h6>    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/app-version-warning.blade.php
@extends('layouts.admin')
@section('content')
<?php
    $title = 'Demo Version';
  

?>
<style>
.card{
    min-height:450px;
    margin-top: 0px;
}
</style>
<section class="rightside-main">
    <div class="container-fluid">
        <div class="page-top">
            <div class="page-header borderless">
                <h4><?php echo $title; ?></h4>   
            </div>
            <div class="page-berdcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard')}}">
                            <i class="fa fa-home"></i> Dashboard
                        </a>
                    </li>
                    <!-- <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard')}}">Dashboard</a>
                    </li> -->
                    <li class="breadcrumb-item">
                        <a href="#">{{$title}}</a>
                    </li>
                </ul>       
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 pr-0">
                @include('includes.admin.settings')
            </div>
            <div class="col-md-9 pl-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card table-card">
                            <div class="card-header borderless">
                                <h3><?php echo $title;?></h3>
                            </div>
                            <div class="card-body">
                                <h6>This Feature Is Not Available For Demo Version.</h6>    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/candidates-videos.blade.php
@extends('layouts.admin')
@section('content')
<?php
   if($action == 'edit'){
    $title = 'Edit Users';
    $readonly="";
}else if($action == 'add') {
    $title = 'Add Users';
    $readonly="";
}else if($action == 'view') {
    $title = 'View Users';
    $readonly='readonly';
}else{
    $title = 'Copy Users';
    $readonly="";
}

$currentPath =  route('admin.candidates.index').'/';
$videoUpload=asset(Storage::url('public/videos/'.$id)).'/';
?>
<section class="rightside-main">
	<div class="container-fluid">
        <div class="page-top">
            <div class="page-header borderless ">
                <h4><?php echo $title;?></h4>   
            </div>
            <div class="page-berdcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard')}}">
                            <i class="fa fa-home"></i> Dashboard
                        </a>
                    </li>
                    <!-- <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard')}}">Dashboard</a>
                    </li> -->
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.candidates.index')}}">Users Management</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="active" href="#"><?php echo $title;?></a>
                    </li>
                </ul>       
            </div>
        </div>
        <div class="card table-card ">
            <div class="row card-header borderless ">
                    <div class="col-md-12 col-lg-12">
                        <h3><?php echo $title;?></h3>
                    </div>
                    
                </div>
           
                    <div class="card-body">
                        <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <ul class="row nav nav-tabs md-tabs" role="tablist">
                                <li class="col-md-6 nav-item">
                                    <a class="nav-link " href="<?php echo $currentPath.$action.'/'.$id ?>" ><i class="fa fa-home" aria-hidden="true"></i> &nbsp;General</a>
                                    <div class="slide"></div>
                                </li>
                            
                                <li class="nav-item col-md-6">
                                    <a class="nav-link active" href="<?php echo $currentPath.$action.'/videos/'.$id ?>" ><i class="fa fa-caret-square-o-right" aria-hidden="true"></i> &nbsp;Videos</a>
                                    <div class="slide"></div>
                                </li>
                                
                            </ul>
                        </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                    </ul>
                                </div>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                        <div class="title_link"> 
                                    <h4><i class="fa fa-caret-square-o-right" aria-hidden="true"></i> Videos</h4>
                                </div> 
                                <div class="row video">  
                                    <?php foreach($videos as $video) {  ?>
                                    <div class="col-md-4 inner_video">
                                        <div class="video_div">
                                            <video width="100%" height="100%" controls>
                                                <source src="<?php echo $videoUpload.$video->video; ?>" type="video/mp4">
                                            </video>
                                            <!-- <img src="<?php //echo $videoUpload.'gif/'.$video->gif; ?>"> -->
                                        </div>
                                        <!-- <div class="title_heading"><?php //echo $video->title; ?></div> -->
                                    </div>
                                    <?php }?> 
                                </div>
                                @if($videos_total_count > 6)
                                <div class="row" style="margin:auto;">
                                     <div class="load_more">
                                     <i class="fa fa-spinner spinner" aria-hidden="true"></i> Load More..
                                    </div>
                                 </div> 
                                 @elseif($videos_total_count == 0)
                                 <div class="align-center">No Record..</div>   
                                 @endif  
                        
                        </div>
                            <input type="hidden" id="id" value="<?php echo $id ?>"> 
                            <input type="hidden" id="loaded_videos" value="<?php echo $loaded_videos; ?>">  
                            <input type="hidden" id="videos_total_count" value="<?php echo $videos_total_count; ?>">
                      </div>
                </div>
            </div>
        </div>
</section>
<script type="text/javascript">

$(function () {
    
    $(".popup img").click(function () {
        var $src = $(this).attr("src");
        $(".show").fadeIn();
        $(".img-show img").attr("src", $src);
    });
    
    $("span, .overlay").click(function () {
        $(".show").fadeOut();
    });
    
});
var offset=0;

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
    }
});


$(".load_more").click(function(e){
    var id=$('#id').val()
    var loaded_videos=$('#loaded_videos').val();
    var videos_total_count=$('#videos_total_count').val();
    offset=offset+6;
    $('.spinner').show();
    $.ajax({
            url: "<?php echo $currentPath;?>loadMoreVideos",
            type:'POST',
            data: {offset:offset,id:id,loaded_videos:loaded_videos},
            success: function(res) {
                var data=JSON.parse(res);
                // alert(data.loaded_videos);
                if(data.html_data!=""){
                    $(".video").append(data.html_data);
                    $('#loaded_videos').val(data.loaded_videos);
                    $('.spinner').hide();
                    
                    if(videos_total_count<=data.loaded_videos){
                        $('.load_more').hide();
                    }
                }else{
                    $('.load_more').hide();
                }
            }
        }); 
    });
</script>
@endsection

resources/views/admin/categories-create.blade.php
@extends('layouts.admin')
@section('content')
<?php
if ($action == 'edit') {
    $title = 'Edit Category';
    $readonly = "";
} else if ($action == 'add') {
    $title = 'Add Category';
    $readonly = "";
} else if ($action == 'view') {
    $title = 'View Category';
    $readonly = 'readonly';
} else {
    $title = 'Copy Category';
    $readonly = "";
}
?>

<div class="col-lg-12">
    <div class="card customers-profile">
        <h3><?php echo $title; ?></h3>
        <div class="row">
            <div class="col-lg-12 col-md-12">
                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
            </div>
        </div>
        <?php
        if ($action == 'edit') { ?>
            <form role="form" action="{{url( config('app.admin_url') .'/categories/'.$id)}}" method="post">
                {{ method_field('PUT') }}
            <?php } else { ?>
                <form role="form" action="{{url( config('app.admin_url') .'/categories')}}" method="post">
                <?php } ?>
                {{ csrf_field() }}
                <div class="row">

                    <div class="col-lg-12 ">
                        <div class="padding20">


                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="fld">
                                        <label for="cat_name" class="control-label"> <small class="req text-danger">* </small>Category Name</label>

                                        <?php
                                        if (old('cat_name') != '') {
                                            $cat_name = old('cat_name');
                                        } else if (isset($category->cat_name) && $category->cat_name != '') {
                                            $cat_name = $category->cat_name;
                                        } else {
                                            $cat_name = '';
                                        }
                                        ?>
                                        <input type="text" class="form-control" name="cat_name" value="<?php echo $cat_name; ?>" {{$readonly}}>


                                    </div>

                                </div>
                                <div class="col-lg-6">
                                    <div class="fld">
                                        <label for="rank" class="control-label"> <small class="req text-danger">* </small>Rank</label>
                                        <?php
                                        if (old('rank') != '') {
                                            $rank = old('rank');
                                        } else if ($action != 'add') {
                                            if ($category->rank == '0') {
                                                $rank = "0";
                                            } else {
                                                $rank = $category->rank;
                                            }
                                        } else {
                                            $rank = '';
                                        }
                                        ?>
                                        <input type="number" class="form-control" name="rank" value="<?php echo $rank; ?>" {{$readonly}}>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="c-invoice" <?php if ($action == 'view') {
                                            echo "style='display:none'";
                                        } ?>>
                    <button type="submit" class="btn btn-info button-green b-shadow">Save</button>
                </div>
            </form>
    </div>

</div>


@endsection

resources/views/admin/change_password.blade.php
@extends('layouts.admin')
@section('content')
<?php
$title = "Change Password";
?>
<style>
    .main_cat .select2-container--default .select2-selection--single {
        background-color: #fff;
        border: 0px solid #aaa;
        border-radius: 0px;
        width: 100%;
        padding: 5px;
    }

    .main_cat .select2-container--default .select2-selection--single .select2-selection__rendered {
        background: #fff;
        padding: 5px;
        height: 40px;
        border: 1px solid #ccc;
    }

    .main_cat .select2-selection__choice,
    .main_cat .select2-selection__choice__remove {
        color: #fff;
    }

    .card {
        min-height: 450px;
        margin-top: 0px;
    }
</style>
<div class="row">
    <div class="col-md-3">
        @include('includes.admin.settings')
    </div>
    <div class="col-md-9 ">
        <div class="row ">
            <div class="col-md-12 col-lg-12">
                <div class="card customers-profile">

                    <h3><?php echo $title; ?></h3>


                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ $message }}</strong>
                                    <?php Session::forget('success'); ?>
                                </div>
                                @endif
                                @if ($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{!! $message !!}</strong>
                                    <?php Session::forget('error'); ?>
                                </div>
                                @endif
                                @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                                @endif
                            </div>
                        </div>
                        <form class="form-horizontal" role="form" action="{{route('admin.change_password.update')}}" method="post" id="form_sample_1">
                            {{ csrf_field() }}
                            <div class="form-body">
                                <div class="form-group row">
                                    <label class="col-md-3 control-label">Old Password <span class="required" aria-required="true"> * </span></label>
                                    <div class="col-md-5">
                                        <input type="password" name="old_password" id="old_password" class="form-control" placeholder="Old Password" autofocus value="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 control-label">New Password <span class="required" aria-required="true"> * </span></label>
                                    <div class="col-md-5">
                                        <input type="password" name="new_password" id="new_password" class="form-control" placeholder="New Password" autofocus value="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 control-label">Confirm Password <span class="required" aria-required="true"> * </span></label>
                                    <div class="col-md-5">
                                        <input type="password" name="confirm_password" class="form-control" placeholder="Confirm Password" autofocus value="">
                                    </div>
                                </div>
                            </div>
                            <div class="row margin-tp-bt-10">
                                <div class="col-lg-12 col-md-12">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <button type="button" class="btn btn-danger btn-shadow" onclick="document.location.href='{{ route('admin.dashboard') }}'">Cancel</button>
                                </div>
                            </div>
                        </form>


                        <!-- </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/img.blade.php
<img src="{{$img}}" >