routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

$adminRoute = config('app.admin_url');

$webRoute = config('app.web_url');

Route::get('/script/moveChatOldToNew', 'ScriptController@moveChatOldToNew')->name('moveChatOldToNew');

Route::get('test', 'IndexController@test')->name('test');
Route::group(['prefix' => $webRoute, 'namespace' => 'Web', 'as' => 'web.'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login-user', 'Auth\LoginController@login')->name('loginUser');
    Route::post('/social-register', 'Auth\LoginController@socialRegister')->name('socialRegister');
    Route::get('/register-user', 'Auth\RegisterController@index')->name('register');
    Route::post('/register-submit', 'Auth\RegisterController@register')->name('registerUser');
    Route::get('/logout-user', 'WebController@logout')->name('logout');
    Route::get('/login-email-verify/{email}', 'Auth\LoginController@loginEmailVerify')->name('login-email-verify');

    Route::get('/email-verify/{user}', 'Auth\RegisterController@emailVerify', function (Request $request) {
        if (!$request->hasValidSignature()) {
            abort(401);
        }

    })->name('email-verify')->middleware('signed');

    // Password Reset Routes...
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('/user-password-changed', 'ForgotPasswordController@passwordChanged')->name('passwordChanged');
        Route::get('/set-password/{user}', 'ForgotPasswordController@setPassword', function (Request $request) {
            if (!$request->hasValidSignature()) {
                abort(401);
            }

        })->name('set-password')->middleware('signed');
    });

    Route::get('/', 'WebController@home')->name('home');
    Route::get('/front/video/{id}', 'WebController@videoInfo')->name('videoInfo');
    Route::get('/front/video/view/{id}', 'WebController@videoViewed')->name('videoViewed');
    Route::get('/front/video/comments/{id}/{type}', 'WebController@videoComments')->name('videoComments');
    Route::get('/privacy-policy', 'PageController@index')->name('privacy-policy')->defaults('slug', 'privacy-policy');
    Route::get('/terms', 'PageController@index')->name('terms')->defaults('slug', 'terms');
    Route::get('/data-delete', 'PageController@index')->name('data-delete')->defaults('slug', 'data-delete');

    Route::group(['middleware' => ['auth:web']], function () {
        Route::post('/front/video/comments/{id}', 'WebController@videoPostComments')->name('videoPostComments');
        Route::get('/front/video/like/{id}', 'WebController@videoLike')->name('videoLike');
        Route::get('/edit-profile/{id}', 'UserController@editUserProfile')->name('editUserProfile');
        Route::post('/edit-profile/{id}', 'UserController@updateUserProfile')->name('updateUserProfile');
        Route::get('/remove-profile-pic', 'UserController@removeProfilePic')->name('removeProfilePic');
        Route::get('/user-follow/{id}', 'UserController@followUnfollowUser')->name('followUnfollowUser');
        Route::get('/user-block/{id}', 'UserController@blockUnblock')->name('blockUnblock');
        Route::get('/notifications', 'UserController@userNotifications')->name('userNotifications');
        Route::get('/notificationStatus', 'UserController@notificationStatus')->name('notificationStatus');

        //upload videos
        Route::get('/upload-video', 'UserController@uploadVideo')->name('uploadVideo');
        Route::post('/upload-video', 'UserController@insertVideo')->name('insertVideo');
        Route::post('/delete-video', 'UserController@deleteVideo')->name('deleteVideo');
        Route::get('/video-info-update/{id?}', 'UserController@videoInfoUpdate')->name('video-info-update');
        Route::post('/video-info-submit', 'UserController@videoInfoSubmit')->name('video-info-submit');

        //password change
        Route::get('/change-password', 'UserController@changePassword')->name('changePassword');
        Route::post('/update-password', 'UserController@updatePassword')->name('updatePassword');

        Route::get('followers-list/{id}', 'UserController@followersList')->name('followers-list');
        Route::get('following-list/{id}', 'UserController@followingList')->name('following-list');
        Route::get('blocked-user-list', 'UserController@blockUsersList')->name('blocked-user-list');
        //messenger
        Route::get('/messages', 'MessagesController@index')->name('messages');
        Route::get('/messages/chat/{conversation}', 'MessagesController@chatMessages')->name('messages.chat');
        Route::post('/messages/store/{conversation}', 'MessagesController@storeMessage')->name('messages.store');
        Route::post('/typing/{id}', 'MessagesController@typingMessage')->name('messages.typing');
        Route::post('/message/read/{conversation}', 'MessagesController@readMessage')->name('messages.readMessage');
        Route::post('/messages/delete', 'MessagesController@deleteMessage')->name('messages.messagesDelete');

        Route::get('/conversation/store/{user_id}', 'ConversationController@store')->name('conversation.store');
        Route::get('/conversation/get', 'ConversationController@index')->name('conversation.get');
        Route::post('/conversation/delete', 'ConversationController@deleteMessage')->name('conversation.deleteMessage');

    });

    //Social login
    Route::get('auth/google', 'Auth\LoginController@redirectToGoogle')->name('googleLogin');
    Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback')->name('googleCallback');

    Route::get('auth/facebook', 'Auth\LoginController@redirectToFacebook')->name('facebookLogin');
    Route::get('auth/facebook/callback', 'Auth\LoginController@handleFacebookCallback')->name('facebookCallback');

    Route::get('/profile/{id}', 'UserController@userProfile')->name('userProfile');

    //firebase notification
    Route::post('/save-token', 'NotificationController@saveToken')->name('saveToken');
    Route::post('/send-notification', 'NotificationController@sendNotification')->name('sendNotification');
    Route::get('/test-notification', 'NotificationController@testNotification')->name('testNotification');

    Route::get('/leuke-search', 'UserController@leukeSearch')->name('leukeSearch');
    Route::get('search-all', 'WebController@searchAll')->name('searchAll');
    Route::get('tag-videos/{val}', 'WebController@searchTagVideos')->name('tagVideos');
});

Route::group(['prefix' => $adminRoute, 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    // Routes without auth check for guest customers
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login')->name('loginPost');
    Route::get('/register', 'Auth\RegisterController@index')->name('register');
    Route::post('/register', 'Auth\RegisterController@register')->name('registerPost');
    Route::get('/logout', 'AdminController@logout')->name('logout');

    // Routes with auth check for logged in admin
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/dashboard', 'AdminController@index')->name('dashboard');
        Route::get('/change_password/', 'AdminController@changePassword')->name('change_password.index')->middleware('app_version_check');
        Route::post('/update_password/', 'AdminController@updatePassword')->name('change_password.update');

        // categories management system ( Listing, Add, Edit, Delete , Copy )
        Route::resource('categories', 'CategoryController');
        Route::post('/categories/delete', 'CategoryController@delete')->name('categories_delete');
        Route::get('/categories/create/{category_id?}', 'CategoryController@create')->name('categories_create');
        Route::get('/categories/{category_id}/view', 'CategoryController@view')->name('categories_view');
        Route::get('/categories/{category_id}/copy', 'CategoryController@copyContent')->name('categories_copy');
        Route::get('/categories/{category_id}/edit', 'CategoryController@edit')->name('categories_edit');
        Route::post('/categories/server_processing', 'CategoryController@serverProcessing')->name('categories_server_processing');

        Route::resource('sounds', 'SoundController');
        Route::post('/sounds/delete', 'SoundController@delete')->name('sounds_delete');
        Route::post('/sounds/select_cat', 'SoundController@select_cat')->name('sounds_select_cat');
        Route::post('/sounds/create', 'SoundController@create')->name('sounds_create');
        Route::get('/sounds/{user_id}/copy', 'SoundController@copyContent')->name('sounds_copy');
        Route::get('/sounds/{user_id}/view', 'SoundController@view')->name('sounds_view');
        Route::get('/sounds/detail/{payment_id}', 'SoundController@detail')->name('sounds_detail');
        Route::post('/sounds/server_processing', 'SoundController@serverProcessing')->name('sounds_server_processing');
        Route::post('/sounds/audio_play', 'SoundController@audio_play')->name('audio_play');

        Route::resource('videos', 'VideoController');
        Route::post('/videos/delete', 'VideoController@delete')->name('videos_delete');
        Route::post('/videos/create', 'VideoController@create')->name('videos_create');

resources/views/includes/admin/settings.blade.php
<div class="card customers-profile-menu">
    <!-- <h4>Company Name</h4> -->
    <ul class="tab-setting">
        <li><a href="{{ route('admin.settings') }}"><i class="bi bi-gear-fill"></i> Global Settings</a></li>
        <li><a href="{{ route('admin.ad_settings') }}"><i class="bi bi-badge-ad-fill"></i> Ads Settings</a></li>
        <li><a href="{{ route('admin.mail_settings') }}"><i class="bi bi-envelope-fill"></i> Mail Settings</a></li>
        <li><a href="{{ route('admin.nsfw_settings') }}"><i class="fa fa-user-secret"></i> Video Moderation Settings</a></li>
        <li><a href="{{ route('admin.change_password.index') }}"><i class="bi bi-lock"></i> Change Password</a></li>
        <li><a href="{{ route('admin.home_settings') }}"><i class="bi bi-house-fill"></i> Home Screen</a></li>
        <li><a href="{{ route('admin.social_settings') }}"><i class="bi bi-globe2"></i> Social Login</a></li>
        <li><a href="{{ route('admin.pusher_settings') }}"><i class="bi bi-bell-fill"></i> Pusher Settings</a></li>
        <li><a href="{{ route('admin.social_media_links') }}"><i class="bi bi-link"></i> Social Media Links</a></li>
        <li><a href="{{ route('admin.app_settings') }}"><i class="bi bi-gear-wide-connected"></i> App Settings</a></li>
        <li><a href="{{ route('admin.storage_settings') }}"><i class="bi bi-server"></i> Storage Settings</a></li>
        <li><a href="{{ route('admin.google_captcha') }}"><i class="bi bi-shuffle"></i> Google Captcha Settings</a></li>
        <li><a href="{{ route('admin.chat-migration') }}"><i class="bi bi-chat"></i> Chat Migration</a></li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        var current = location.pathname;
        $('.tab-setting a').each(function() {
            var $this = $(this);
            // if the current path is like this link, make it active
            if ($this.attr('href').indexOf(current) !== -1) {
                $this.addClass('green');
            }
        })
    });
</script>
<style type="text/css">
    /* .btn-tab-setting {
        background-color: white !important;
        color: black !important;
        padding: 13px 20px;
        border-bottom: 1px solid #ccc;
        line-height: 20px;
        text-align: left;

    } */

    /* .btn-tab-setting.active {
        background-color: black !important;
        border: 2px solid black !important;
        color: white !important;
    } */

    /* .tab-setting {
        box-shadow: 0 2px 10px -1px rgba(69, 90, 100, 0.3);
        border: none !important;
        padding: 10px 10px;
        border-radius: 8px;
        background: white;
        height: 100%;
    } */
</style>

resources/views/includes/admin/sidebar.blade.php
<!-- mob menu -->

<div class="topnav d-lg-none">
    <a href="#home" class="active text-center"><img class="img-fluid" src="{{ MyFunctions::getLogo() }}" width="130px"></a>
    <div id="myLinks">
        <nav class="sidebar py-2 mb-4">
            <ul class="nav flex-column" id="nav_accordion">
                <li class="nav-item"><a href="{{ route('admin.dashboard') }}" class="<?php echo (Route::currentRouteName()=='admin.dashboard') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-house-fill"></i> Dashbroard</a></li>
                <li class="nav-item"><a href="{{ route('admin.categories.index')}}" class=" nav-link"><i class="bi bi-list-ul"></i> Categories</a></li>
                <li class="nav-item"><a href="{{ route('admin.sounds.index')}}" class=" nav-link"><i class="bi bi-music-note-list"></i> Sounds</a></li>
                <li class="nav-item has-submenu">
                    <a class="nav-link" href="#"><i class="bi bi-people-fill"></i> Users <i class="fa fa-caret-down float-lg-end"></i></a>
                    <ul class="submenu collapse">
                        <li><a class="nav-link" href="{{ route('admin.candidates.index')}}/1"><i class="fa fa-angle-right" aria-hidden="true"></i> Active</a></li>
                        <li><a class="nav-link" href="{{ route('admin.candidates.index')}}/0"><i class="fa fa-angle-right" aria-hidden="true"></i> Inactive</a></li>

                    </ul>
                </li>
                <li class="nav-item has-submenu">
                    <a class="nav-link" href="#"><i class="bi bi-bookmark-fill"></i> Verification <i class="fa fa-caret-down float-lg-end"></i></a>
                    <ul class="submenu collapse">
                        <li><a class="nav-link" href="{{ route('admin.user-verify.index', ['type'=>'A'])}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Verified</a></li>
                        <li><a class="nav-link" href="{{ route('admin.user-verify.index', ['type'=>'P'])}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Pending</a></li>
                        <li><a class="nav-link" href="{{ route('admin.user-verify.index', ['type'=>'R'])}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Rejected</a></li>

                    </ul>
                </li>
                <li class="nav-item"><a href="{{ route('admin.videos.index')}}" class=" nav-link"><i class="bi bi-camera-video-fill"></i> Videos</a></li>
                <li class="nav-item"><a href="{{ route('admin.flagvideos.index')}}" class=" nav-link"><i class="bi bi-camera-video-fill"></i> Flaged Videos</a></li>
                <li class="nav-item"><a href="{{ route('admin.tags.index')}}" class=" nav-link"><i class="bi bi-tags-fill"></i> Tags</a></li>
                <li class="nav-item"><a href="{{ route('admin.reports.index')}}" class=" nav-link"><i class="bi bi-layout-text-sidebar-reverse"></i> Reports</a></li>
                <li class="nav-item"><a href="{{ route('admin.settings')}}" class=" nav-link"><i class="bi bi-gear-fill"></i> Settings</a></li>
                <li class="nav-item"><a href="{{ route('admin.app_config_settings')}}" class=" nav-link"><i class="bi bi-gear-wide-connected"></i> App Theme Settings</a></li>
                <li class="nav-item"><a href="{{ route('admin.pages.index')}}" class=" nav-link"><i class="bi bi-pencil-square"></i> Pages</a></li>
                <li class="nav-item"><a href="{{ route('admin.sponsors.index')}}" class=" nav-link"><i class="bi bi-people-fill"></i> Sponsors</a></li>
                <li class="nav-item has-submenu">
                    <a class="nav-link" href="#"><i class="bi bi-check2-circle"></i> Engagement <i class="fa fa-caret-down float-lg-end"></i></a>
                    <ul class="submenu collapse">
                        <li><a class="nav-link" href="{{ route('admin.comments.index')}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Comments</a></li>
                        <li><a class="nav-link" href="{{ route('admin.chats.index')}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Chat</a></li>
                        <li><a class="nav-link" href="{{ route('admin.likes.index')}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Likes</a></li>

                    </ul>
                </li>
                <li class="nav-item"><a href="{{ route('admin.logout') }}" class="active-links nav-link"><i class="bi bi-house-fill"></i> Logout</a></li>

            </ul>
        </nav>
    </div>
</div>


<!-- menu -->
<div class="col-xxl-2 col-xl-2 col-lg-3 menu-main d-none d-lg-block pe-0">

    <div class="logo">
        <a href="index.php"><img class="img-fluid" src="{{ MyFunctions::getLogo() }}" width="130px"></a>
    </div>
    <nav class="sidebar py-2 mb-4">
        <ul class="nav flex-column" id="nav_accordion">
            <li class="nav-item"><a href="{{ route('admin.dashboard')}}" class="<?php echo (Route::currentRouteName()=='admin.dashboard') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-house-fill"></i> Dashbroard</a></li>
            <li class="nav-item"><a href="{{ route('admin.categories.index')}}" class="<?php echo (Route::currentRouteName()=='admin.categories.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-list-ul"></i> Categories</a></li>
            <li class="nav-item"><a href="{{ route('admin.sounds.index')}}" class="<?php echo (Route::currentRouteName()=='admin.sounds.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-music-note-list"></i> Sounds</a></li>
            <li class="nav-item has-submenu">
                <a class="<?php echo (Route::currentRouteName()=='admin.candidates.show') ? 'active-links' : ''; ?> nav-link" href="#"><i class="bi bi-people-fill"></i> Users <i class="fa fa-caret-down float-lg-end"></i></a>
                <ul class="submenu collapse <?php echo (Route::currentRouteName()=='admin.candidates.show') ? 'show' : ''; ?>">
                    <li><a class="nav-link <?php echo ((Route::currentRouteName()=='admin.candidates.show') && (Request::getPathInfo()=='/admin/candidates/1')) ? 'active' : ''; ?> " href="{{ route('admin.candidates.index')}}/1"><i class="fa fa-angle-right" aria-hidden="true"></i> Active</a></li>
                    <li><a class="nav-link <?php echo ((Route::currentRouteName()=='admin.candidates.show') && (Request::getPathInfo()=='/admin/candidates/0')) ? 'active' : ''; ?>" href="{{ route('admin.candidates.index')}}/0"><i class="fa fa-angle-right" aria-hidden="true"></i> Inactive</a></li>

                </ul>
            </li>
            <li class="nav-item has-submenu">
                <a class="<?php echo (Route::currentRouteName()=='admin.user-verify.index') ? 'active-links' : ''; ?> nav-link" href="#"><i class="fa fa-check-circle"></i> Verification <i class="fa fa-caret-down float-lg-end"></i></a>
                <ul class="submenu collapse <?php echo (Route::currentRouteName()=='admin.user-verify.index') ? 'show' : ''; ?>">
                    <li><a class="nav-link <?php echo ((Route::currentRouteName()=='admin.user-verify.index') && Request::query()['type']=='A') ? 'active' : ''; ?>" href="{{ route('admin.user-verify.index', ['type'=>'A'])}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Verified</a></li>
                    <li><a class="nav-link <?php echo ((Route::currentRouteName()=='admin.user-verify.index') && Request::query()['type']=='P') ? 'active' : ''; ?>" href="{{ route('admin.user-verify.index', ['type'=>'P'])}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Pending</a></li>
                    <li><a class="nav-link <?php echo ((Route::currentRouteName()=='admin.user-verify.index') && Request::query()['type']=='R') ? 'active' : ''; ?>" href="{{ route('admin.user-verify.index', ['type'=>'R'])}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Rejected</a></li>

                </ul>
            </li>
            <li class="nav-item"><a href="{{ route('admin.videos.index')}}" class="<?php echo (Route::currentRouteName()=='admin.videos.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-camera-video-fill"></i> Videos</a></li>
            <li class="nav-item"><a href="{{ route('admin.flagvideos.index')}}" class="<?php echo (Route::currentRouteName()=='admin.flagvideos.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-camera-video-fill"></i> Flaged Videos</a></li>
            <li class="nav-item"><a href="{{ route('admin.tags.index')}}" class="<?php echo (Route::currentRouteName()=='admin.tags.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-tags-fill"></i> Tags</a></li>
            <li class="nav-item"><a href="{{ route('admin.reports.index')}}" class="<?php echo (Route::currentRouteName()=='admin.reports.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-layout-text-sidebar-reverse"></i> Reports</a></li>
            <li class="nav-item"><a href="{{ route('admin.settings')}}" class="<?php echo (Route::currentRouteName()=='admin.settings') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-gear-fill"></i> Settings</a></li>
            <li class="nav-item"><a href="{{ route('admin.app_config_settings')}}" class="<?php echo (Route::currentRouteName()=='admin.app_config_settings') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-gear-wide-connected"></i> App Theme Settings</a></li>
            <li class="nav-item"><a href="{{ route('admin.pages.index')}}" class="<?php echo (Route::currentRouteName()=='admin.pages.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-pencil-square"></i> Pages</a></li>
            <li class="nav-item"><a href="{{ route('admin.sponsors.index')}}" class="<?php echo (Route::currentRouteName()=='admin.sponsors.index') ? 'active-links' : ''; ?> nav-link"><i class="bi bi-people-fill"></i> Sponsors</a></li>
            <li class="nav-item has-submenu">
                <a class="<?php echo (Route::currentRouteName()=='admin.comments.index' || Route::currentRouteName()=='admin.chats.index' || Route::currentRouteName()=='admin.likes.index') ? 'active-links' : ''; ?> nav-link" href="#"><i class="bi bi-bookmark-fill"></i> Engagement <i class="fa fa-caret-down float-lg-end"></i></a>
                <ul class="submenu collapse <?php echo (Route::currentRouteName()=='admin.comments.index' || Route::currentRouteName()=='admin.chats.index' || Route::currentRouteName()=='admin.likes.index') ? 'show' : ''; ?>">
                    <li><a class="nav-link <?php echo (Route::currentRouteName()=='admin.comments.index') ? 'active': ''; ?>" href="{{ route('admin.comments.index')}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Comments</a></li>
                    <li><a class="nav-link <?php echo (Route::currentRouteName()=='admin.chats.index') ? 'active' : ''; ?>" href="{{ route('admin.chats.index')}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Chat</a></li>
                    <li><a class="nav-link <?php echo (Route::currentRouteName()=='admin.likes.index') ? 'active' : ''; ?>" href="{{ route('admin.likes.index')}}"><i class="fa fa-angle-right" aria-hidden="true"></i> Likes</a></li>

                </ul>
            </li>
            <li class="nav-item"><a href="{{ route('admin.logout') }}" class=" nav-link"><i class="bi bi-house-fill"></i> Logout</a></li>

        </ul>
    </nav>
</div>

resources/views/includes/admin/topbar.blade.php
<div class="topbar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6  col-6">
        <div class="top-right-liks">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><bi class="bi bi-house-fill"></bi> Dashboard</a></li>
              <?php if (isset($menu)) { ?>
                <li class="breadcrumb-item active" aria-current="page"><a href="{{ $menuUrl }}">{{ $menu }}</a></li>
              <?php } ?>
              <?php if (isset($submenu)) { ?>
                <li class="breadcrumb-item active" aria-current="page"><a href="{{ $submenuUrl }}">{{ $submenu }}</a></li>
              <?php } ?>
            </ol>
          </nav>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-6">
        <div class="top-right-liks pull-right">
          <!-- <ul>
            <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="bi bi-chat-text-fill"></i> </a></li>
            <li><a href="#"><i class="bi bi-bell-fill"></i></a></li>
            <li><a href="#"><i class="bi bi-slack"></i></a></li>
            <li><a href="#"><i class="bi bi-grid-fill"></i></a>
            </li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
</div>